sudo: requred
services:
    - docker
    
before_install:
    - docker build -t andreymaltsev/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true andreymaltsev/react-test npm test
    
after_success:
    - docker build -t andreymaltsev/multi-client ./client
    - docker build -t andreymaltsev/multi-nginx ./nginx
    - docker build -t andreymaltsev/multi-server ./server
    - docker build -t andreymaltsev/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin     
    # Take those images and push them to docker hub
    - docker push andreymaltsev/multi-client  
    - docker push andreymaltsev/multi-nginx
    - docker push andreymaltsev/multi-server
    - docker push andreymaltsev/multi-worker  
       
    
